environment:
  matrix:
    - PYTHON: "C:\\Python37-x64"
      PYTHON_VERSION: "3.7.x"
      PYTHON_ARCH: "64"
matrix:
  fast_finish: true
install:
  - "choco install rust-ms"
  - "refreshenv"
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "python -m pip install --upgrade setuptools pip tox"
build: off
before_test:
  - "python --version"
  - "python -c \"import sys; print(sys.executable)\""
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""
test_script:
  - "tox"
after_test:
  - "make"
  - ".\\dist\\Gridsync\\Gridsync.exe --version"
  - ".\\dist\\Gridsync\\Tahoe-LAFS\\tahoe.exe --version-and-path"
  - "python .\\scripts\\make_archive.py"
  - "move .\\dist\\Gridsync.zip .\\dist\\Gridsync-Windows.zip"
  - "python .\\scripts\\sha256sum.py .\\dist\\Gridsync-Windows*"
artifacts:
  - path: dist\Gridsync-Windows.zip
    name: Gridsync-Windows.zip
  - path: dist\Gridsync-setup.exe
    name: Gridsync-setup.exe
on_success:
  - "python misc/irc-notify.py [{project_name}:{branch}] {short_commit}: \"{message}\" ({author}) {color_code}3Succeeded,Details: {build_url},Commit: {commit_url}"
on_failure:
  - "python misc/irc-notify.py [{project_name}:{branch}] {short_commit}: \"{message}\" ({author}) {color_code}4Failed,Details: {build_url},Commit: {commit_url}"
notifications:
  - provider: Webhook
    url: https://ci.gridsync.io:8080
#deploy:
#  provider: GitHub
#  auth_token:
#    secure: 7MqXbCzCSmPXcKfaSz1OxAcxgso41W0x6SWQeQiMnRjTbGPn4LqHC6oIuFIsM6g7
#  artifact: dist\Gridsync-Windows.zip, dist\Gridsync-setup.exe
#  description: $(appveyor_repo_commit_message)
#  draft: false
#  prerelease: true
#  force_update: true
#  on:
#    appveyor_repo_tag: true
